config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/:id/welcome', to: "users/registrations#welcome", as: :user_welcome
    get 'users/:id/myshops', to: "users/registrations#myshops", as: :my_shops
  end

  # static pages
  root to: "static#index"
  get '/about', to: "static#about"
  get '/contact', to: "static#contact"
  get '/faq', to: "static#faq"
  get '/terms', to: "static#terms"


  resources :shops
  resources :products
  resources :categories

  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  resources :favorite_products, only: [:index, :create, :destroy]
  resources :favorite_shops, only: [:index, :create, :destroy]
  resources :views, only: [:index]

  resources :socials, only: [:destroy]
  resources :payments, only: [:destroy]

  mount ActionCable.server => '/cable'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shop.rb
require 'elasticsearch/model'

class Shop < ApplicationRecord
  if Rails.env.production?
    Elasticsearch::Model.client = Elasticsearch::Client.new url: ENV['BONSAI_URL'], log: true
  end
  include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks
  after_commit on: [:create] do
    __elasticsearch__.index_document
  end

  after_commit on: [:update] do
    __elasticsearch__.index_document
  end

  after_commit on: [:destroy] do
    __elasticsearch__.delete_document
  end

  has_many :products, dependent: :destroy
  has_many :views, dependent: :destroy
  has_many :socials, dependent: :destroy
  has_many :payments, dependent: :destroy
  belongs_to :user
  belongs_to :category

  accepts_nested_attributes_for :products
  accepts_nested_attributes_for :socials
  accepts_nested_attributes_for :payments

  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :image, ShopUploader

  geocoded_by :location
  after_validation :geocode, if: ->(obj){ obj.location.present? and obj.location_changed? }
  reverse_geocoded_by :latitude, :longitude

  validates :title, presence: true
  validates :category_id, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  def self.search_with_elasticsearch(*args,&block)
    __elasticsearch__.search(*args, &block)
  end

end

Shop.import force: true

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]
  before_action :correct_user, only: [:edit, :destroy]

  # GET /shops
  # GET /shops.json
  def index

    # search query
    if params[:q].nil?
      @shops = Shop.all
    else
      @shops = Shop.search_with_elasticsearch(params[:q]).records
    end

    if params[:filter].present?
      if params[:filter] == 'name'
        @shops = @shops.order('title ASC')
      elsif params[:filter] == 'date'
        @shops = @shops.order('updated_at DESC')
      elsif params[:filter] == 'location'
        define_location
        @shops = @shops.near([@latitude, @longitude], 8_000_000, order: 'distance')
      end
    else
      @shops = @shops.order('updated_at DESC')
    end

    @shops = @shops.page(params[:page]).per(20)

  end


  # GET /shops/1
  # GET /shops/1.json
  def show
    # friendly id
    @shop = Shop.friendly.find(params[:id])

    # sort products
    @shopProducts = Product.where(shop_id: @shop.id)
    if params[:filter].present?
      if params[:filter] == 'name'
        @shopProducts = @shopProducts.order('name ASC')
      elsif params[:filter] == 'date'
        @shopProducts = @shopProducts.order('updated_at DESC')
      elsif params[:filter] == 'price'
        @shopProducts = @shopProducts.order('price DESC')
      elsif params[:filter] == 'priceA'
        @shopProducts = @shopProducts.order('price ASC')
      end
    else
      @shopProducts = @shopProducts.order('updated_at DESC')
    end

    @shopProducts = @shopProducts.page(params[:page]).per(15)

    # create View
    if current_user
      @view = View.find_or_initialize_by(
        shop_id: @shop.id,
        user_id: current_user.id
      )
      @view.updated_at = Time.now
      @view.save
    end

  end

  # GET /shops/new
  def new
    @shop = Shop.new
    @categories = Category.all

    # if have data
    if current_user.first_name.blank? || current_user.last_name.blank? || current_user.birthday.blank? || current_user.city.blank? || current_user.phone.blank?
      redirect_to edit_user_registration_path(current_user), alert: 'Please provide some details about your identity before creating the shop'
    elsif current_user.shops.length >= 2
      redirect_to user_welcome_path(current_user), alert: 'Sorry, you are limited to creating 2 shops maximum'
    end


  end

  # GET /shops/1/edit
  def edit
    @categories = Category.all
  end

  # POST /shops
  # POST /shops.json
  def create
    @categories = Category.all

    if current_user
      @shop = current_user.shops.build(shop_params)
      # @shop = Shop.new(shop_params)
      respond_to do |format|
        if @shop.save
          format.html {
            # add socials with custom handler
            if params[:shop][:socials_attributes].present?
              params[:shop][:socials_attributes].each do |key, value|
                if value[:link].present?
                  @social = Social.find_or_initialize_by(
                    shop_id: @shop.id,
                    link: value[:link],
                    icon: value[:icon]
                  )
                  @social.link = value[:link]
                  @social.icon = value[:icon]
                  @social.save
                end
              end
            end
            # add payments with custom handler
            if params[:shop][:payments_attributes].present?
              params[:shop][:payments_attributes].each do |key, value|
                if value[:icon].present?
                  @payment = Payment.find_or_initialize_by(
                    shop_id: @shop.id,
                    icon: value[:icon]
                  )
                  @payment.icon = value[:icon]
                  @payment.save
                end
              end
            end

            redirect_to @shop, notice: 'Shop was successfully created.'
          }
          format.json { render :show, status: :created, location: @shop }
        else
          format.html { render :new }
          format.json { render json: @shop.errors, status: :unprocessable_entity }
        end
      end

    else
  		redirect_to new_user_session_path
    end

  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    @categories = Category.all

    respond_to do |format|
      if @shop.update(shop_params)
        format.html {
          # add socials with custom handler
          if params[:shop][:socials_attributes].present?
            params[:shop][:socials_attributes].each do |key, value|
              if value[:link].present?
                @social = Social.find_or_initialize_by(
                  shop_id: @shop.id,
                  link: value[:link],
                  icon: value[:icon]
                )
                @social.link = value[:link]
                @social.icon = value[:icon]
                @social.save
              end
            end
          end
          # add payments with custom handler
          if params[:shop][:payments_attributes].present?
            params[:shop][:payments_attributes].each do |key, value|
              if value[:icon].present?
                @payment = Payment.find_or_initialize_by(
                  shop_id: @shop.id,
                  icon: value[:icon]
                )
                @payment.icon = value[:icon]
                @payment.save
              end
            end
          end

          redirect_to @shop, notice: 'Shop was successfully updated.'
        }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(
        :category_id, :user_id, :title, :image, :description, :location, :email, :phone, :phone_2, :contacts,
        products_attributes: [:shop_id, :image, :name, :price, :description]
      )
      # socials_attributes: [:shop_id, :image, :link, :icon],
      # payments_attributes: [:shop_id, :image, :icon]
    end

    def correct_user
      @targetShop = current_user.shops.friendly.find(params[:id])
      if @targetShop.nil?
        redirect_back(fallback_location: root_path)
        flash[:alert] = 'You dont have an acess to this page'
      end
    end

    def define_location
    	# if have geolocation cookies
    	if !cookies[:geolocation].nil?
    		@location = JSON.parse(cookies[:geolocation]).symbolize_keys
    	else
    		# or detect by ip
    		@ip = request.remote_ip
    		if Rails.env.production?
    			locale = request.location
    			@location = {longitude: locale.longitude, latitude: locale.latitude}
    		else
    			@location = GeoIp.geolocation("192.206.151.131")
    		end
    	end
    	@latitude = @location[:latitude]
    	@longitude = @location[:longitude]
    	cookies[:geolocation] = { value: JSON.generate(@location), expires: Time.now + 3600 * 24 * 7 }
    end

end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.slim
= form_for @shop do |f|
  - if @shop.errors.any?
    #error_explanation
      h2 = "#{pluralize(@shop.errors.count, "error")} prohibited this shop from being saved:"
      ul
        - @shop.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :image
    = f.text_field :image
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :phone
    = f.text_field :phone, class: 'js-mask-phone'
  .field
    = f.label :phone_2
    = f.text_field :phone_2, class: 'js-mask-phone'
  .field
    = f.label :contacts
    = f.text_field :contacts
  .actions = f.submit

app/views/shops/_results.html.slim
.search
  .container
    .row.row--jcsb.row--column--mobile
      .col.col--3-6
        .search__title We have found #{@shops.count(:all)} results!
      .col.col--3-6.text-right.text-center--mobile
        .search__searchbox
          form action="/shops" method="get"
            = text_field_tag :q, params[:q], placeholder: 'search query..'
.container
  .ad-banner.ad-banner--nomb
    - if banner(2).present?
      = banner(2).content.html_safe
.shop
  .container
    .row
      .col.col--auto
        .shop__sortby
          .shop__sortby__title Sort by: 
          .shop__sortby__filters
            .shop__sortby__filter.active[data-filter='date'] Date
            .shop__sortby__filter[data-filter='name'] Name A-Z
            .shop__sortby__filter[data-filter='location'] Location
          
        - @shops.each do |shop|
          .shop__listing data-link=url_for(shop)
            .shop__listing__image
              = image_tag shop.image.thumb
            .shop__listing__content
              .shop__listing__name = shop.title
              .shop__listing__location = shop.location
              .shop__listing__contacts
                span
                  = shop.email
                  |  | 
                span
                  = shop.phone
                  |  | 
                span
                  = shop.phone_2
                  |  | 
                span
                  = shop.contacts

              .shop__listing__description = sanitize(shop.description, :tags=>[]).truncate(200, :separator => " ").html_safe
              .shop__listing__actions
                - if current_user && current_user.id == shop.user.id
                  = link_to 'Edit', edit_shop_path(shop), class: 'btn btn--secondary btn--secondary--edit'
                = link_to 'More details', shop, class: 'btn btn--secondary'
        
        = paginate @shops

app/views/shops/edit.html.slim
- content_for :head do
  title Edit shop on WinSouq Account

.shop
  .container
    .row.white-bg
      .col.col--auto
        = form_for @shop, html: { multipart: true } do |f|
          .shop__hero
            = image_tag @shop.image.hero
            = f.file_field :image
            i.ico.ico-shop-photo
            .shop__hero__title Click to edit photo
          .shop__contacts
            .text-center
              .shop__contacts__title SHOP DETAILS
            .row.row--column--tablet
              .col.col--3-6
                .ui-group.ui-group--quick.mt20
                  = f.text_field :location, placeholder: 'INSERT ADDRESS HERE'
                  .ui-group-edit 
                    | (edit)
                .ui-group.ui-group--quick
                  = f.text_field :email, placeholder: 'EMAIL'
                  .ui-group-edit 
                    | (edit)
                .ui-group.ui-group--quick
                  = f.text_field :phone, placeholder: 'Phone number 1', class: 'js-mask-phone'
                  .ui-group-edit 
                    | (edit)
                .ui-group.ui-group--quick
                  = f.text_field :phone_2, placeholder: 'Phone number 2', class: 'js-mask-phone'
                  .ui-group-edit 
                    | (edit)
                .ui-group.ui-group--quick
                  = f.text_field :contacts, placeholder: 'Contacts'
                  .ui-group-edit 
                    | (edit)
              .col.col--3-6
                .sidebar-title.text-right Social accounts
                .shop__socials
                  / = f.fields_for :socials, [Social.new]*3 do |s|
                  /   = s.text_field :icon
                  /   = s.text_field :link
                  - @shop.socials.each do |s|
                    .shop__social
                      = link_to s, data: { confirm: 'Remove this social media account?' }, method: :delete
                        i.ico.ico-remove data-id="#{s.id}"
                      a href='#{s.link}' target='_blank'
                        i[class="ico ico-social ico-social-#{s.icon}"]
                .text-right
                  a.popup-with-zoom-anim href='#socialModal'
                    i.ico.ico-new-product
                  
                  #socialModalPaste
                  
                .zoom-anim-dialog.mfp-hide#socialModal
                  .h1-title.text-center Add social media account
                  .ui-group.ui-group--select
                    label Select social media
                    select
                      option value='fb' Facebook
                      option value='tw' Twitter
                      option value='rss' Rss
                      option value='gplus' Google Plus
                      option value='vimeo' Vimeo
                      option value='pinterest' Pinterest
                      option value='linedin' Linkedin
                      option value='instagram' Instagram
                      / option value='custom' Add another
                  .ui-group#socialModalImage
                    label Choose image
                    input type='file'
                    
                  .ui-group#socialModalLink
                    label Provide a link
                    input type='text' placeholder='www link..'
                    .ui-group__validation
                  a.btn.btn--secondary type='submit' Add to the shop
            
            .mt20
              = f.submit "Save", class: 'btn btn--secondary'
            
                  
          - if @shop.errors.any?
            #error_explanation
              h2 = "#{pluralize(@shop.errors.count, "error")} prohibited this shop from being saved:"
              ul
                - @shop.errors.full_messages.each do |message|
                  li = message
          
          .row.row--column--tablet
            .col.col--4-6
              .ui-group.shop__verification-form
                label Verification details
                - if @shop.verified
                  p Shop is verified. Thank you
                - else
                  p Please provide prove of ownership and location details via email to
                  a href='mailto:shops@winsouq.com' shops@winsouq.com
                  
                  
              .ui-group
                = f.label :title
                = f.text_field :title
              .ui-group
                = f.label :description
                = f.text_area :description, class: 'tinyMCE'
                
              .ui-group
                label Choose category
                = f.select(:category_id, options_from_collection_for_select(@categories, "id", "name", @shop.category.id), {}, { :multiple => false, :size => 10, :class => "ui-multi-select" } )
                
              .actions 
                = f.submit "Save", class: 'btn btn--secondary'
                
                = link_to 'Delete', @shop, data: { confirm: 'Are you sure?' }, method: :delete, class: 'link--danger'
            
            .col.col--2-6
              .shop__sidebar
                / .sidebar-title Payment options (edit)
                / .shop__payments
                /   - @shop.payments.each do |p|
                /     .shop__payment
                /       = link_to p, data: { confirm: 'Remove this payment method' }, method: :delete
                /         i.ico.ico-remove data-id="#{p.id}"
                /       i[class="ico ico-payment ico-payment-#{p.icon}"]
                /       
                / .text-right
                /   a.popup-with-zoom-anim href='#paymentModal'
                /     i.ico.ico-new-product
                / #paymentModalPaste      
                /   
                / .zoom-anim-dialog.mfp-hide#paymentModal
                /   .h1-title.text-center Add payment method
                /   .ui-group.ui-group--select
                /     label Select payment method
                /     select
                /       option value='paypal' PayPal
                /       option value='visa' Visa
                /       option value='mastercard' Mastercard
                /       option value='maestro' Maestro
                /       option value='wirecard' Wirecard
                /       option value='cash' Cash
                / 
                /   a.btn.btn--secondary type='submit' Add to the shop
                / 
        .row.row--column--tablet
          .col.col--4-6
          
            .shop__products

              - @shop.products.each do |product|
                = form_for product, html: { multipart: true } do |p|
                  .shop__product
                    = hidden_field_tag 'shop_id', @shop.id
                    .shop__product__image
                      = p.file_field :image, :multiple => false
                      = image_tag product.image.thumb
                      i.ico.ico-shop-photo
                      span
                        | Click to add photo
                    .shop__product__content
                      .ui-group.ui-group--small
                        = p.text_field :name, placeholder: 'Enter name'
                      .ui-group.ui-group--small
                        = p.text_field :price, placeholder: 'Enter price'
                      .ui-group.ui-group--small
                        = p.text_field :description, placeholder: 'Enter description'
                      .shop__product__actions
                        = link_to 'Delete', product, data: { confirm: 'Are you sure?' }, method: :delete, class: 'link--danger'
                        = p.submit 'Update', class: 'btn btn--secondary'
            
            
              .shop__products__new
                i.ico.ico-new-product
                .shop__products__new__title Add new Item
                
              = form_for Product.new do |product|
                .shop__product.shop__product--hidden
                  = hidden_field_tag 'shop_id', @shop.id
                  .shop__product__image
                    = product.file_field :image, :multiple => false
                    i.ico.ico-shop-photo
                    span
                      | Click to edit photo
                  .shop__product__content
                    .ui-group.ui-group--small
                      = product.text_field :name, placeholder: 'Enter name'
                    .ui-group.ui-group--small
                      = product.text_field :price, placeholder: 'Enter price'
                    .ui-group.ui-group--small
                      = product.text_field :description, placeholder: 'Enter description'
                    .shop__product__actions
                      = product.submit 'Create', class: 'btn btn--secondary'
              
          // sidebar
          .col.col--2-6

app/views/shops/index.html.slim
- content_for :head do
  title All shops

= render "shops/results"

app/views/shops/show.html.slim
- content_for :head do
  title = @shop.title

.shop
  .container
    .row.white-bg
      .col.col--auto
        .shop__verification
          - if @shop.verified
              i.ico.ico-verified.yes
                .tooltip.bottom
                  .tooltip__content Shop verified
          - else
              i.ico.ico-verified
                .tooltip.bottom
                  .tooltip__content Shop unverified
        .shop__hero
          = image_tag @shop.image.hero
          .shop__hero__title.shop__hero__title--client= @shop.title
        .shop__contacts
          .text-center
            .shop__contacts__title SHOP DETAILS
          .row.row--column--tablet
            .col.col--3-6
              .shop__contact.mt20
                span 
                  | Location: 
                = @shop.location

              .shop__contact
                span 
                  | Email: 
                = @shop.email

              .shop__contact
                span 
                  | Phone: 
                = @shop.phone

              .shop__contact
                span 
                  | Phone2: 
                = @shop.phone_2  

              .shop__contact
                span 
                  | Contacts: 
                = @shop.contacts
              .shop__contact
                - if @shop.user != current_user
                  br
                  = link_to "Send message to #{@shop.user.name}", new_personal_message_path(receiver_id: @shop.user), class: 'btn btn--secondary'
              
              - if current_user && @shop.user == current_user
                = link_to "Edit", edit_shop_path(@shop), class: 'btn btn--secondary btn--secondary--edit mt10'


            .col.col--3-6
              .shop__socials
                - @shop.socials.each do |s|
                  .shop__social
                    a href='#{s.link}' target='_blank'
                      i[class="ico ico-social ico-social-#{s.icon}"]
                  
        .row.row--column--tablet
          .col.col--4-6
            .shop__content
              .h3-title Featured products
              .shop__products-list
                - @shopProducts.each do |product|
                  .shop__product-box
                    .shop__product-box__favorite
                      - unless current_user && current_user.favorite_products.exists?(id: product.id)
                        = link_to '+ <i class="ico ico-like"></i>'.html_safe, favorite_products_path(product_id: product), method: :post
                      - else
                        = link_to '- <i class="ico ico-like"></i>'.html_safe, favorite_product_path(product), method: :delete

                    .shop__product-box__description
                      = product.description
                    .shop__product-box__image
                      = image_tag product.image.thumb
                    .shop__product-box__info
                      .shop__product-box__info__name
                        = product.name
                      .shop__product-box__info__price
                        = product.price
                        
                = paginate @shopProducts
                    
          // sidebar
          .col.col--2-6
            .shop__sidebar
              .shop__sidebar__favorite
                - unless current_user && current_user.favorite_shops.exists?(id: @shop.id)
                  = link_to 'favourite this store'.html_safe, favorite_shops_path(shop_id: @shop.id), method: :post
                - else
                  = link_to 'remove from favourites'.html_safe, favorite_shop_path(@shop.id), method: :delete
              
              .ad-banner
                - if banner(1).present?
                  = banner(1).content.html_safe
                  
              .sidebar-title Shop on map
              - if @shop.location.present?
                script async="" defer="defer" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBUOfU8DspyA0ie-D0DSwWN4DdjjgpGenI&callback=initMap" 
                iframe allowfullscreen="" frameborder="0" height="300" src="https://www.google.com/maps/embed/v1/place?q=#{"#{@shop.latitude}"}, #{"#{@shop.longitude}"}&key=AIzaSyBUOfU8DspyA0ie-D0DSwWN4DdjjgpGenI" style="border:0" width="100%" 

              .sidebar-title.mt30 SoRt products
              .shop__sorting
                .shop__sorting__filter.active[data-filter='date'] Sort by <span>Date</span>
                .shop__sorting__filter[data-filter='name'] Sort by <span>Name</span>
                .shop__sorting__filter[data-filter='priceA'] Sort by <span>Price ASC</span>
                .shop__sorting__filter[data-filter='price'] Sort by <span>Price DESC</span>
              
              / .sidebar-title Payment options
              / .shop__payments
              /   - @shop.payments.each do |p|
              /     .shop__payment
              /       i[class="ico ico-payment ico-payment-#{p.icon}"]
                