config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/:id/welcome', to: "users/registrations#welcome", as: :user_welcome
    get 'users/:id/myshops', to: "users/registrations#myshops", as: :my_shops
  end

  # static pages
  root to: "static#index"
  get '/about', to: "static#about"
  get '/contact', to: "static#contact"
  get '/faq', to: "static#faq"
  get '/terms', to: "static#terms"


  resources :shops
  resources :products
  resources :categories

  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  resources :favorite_products, only: [:index, :create, :destroy]
  resources :favorite_shops, only: [:index, :create, :destroy]
  resources :views, only: [:index]

  resources :socials, only: [:destroy]
  resources :payments, only: [:destroy]

  mount ActionCable.server => '/cable'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/banner.rb
class Banner < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :shops

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

  validates :author, uniqueness: {scope: :receiver}

  scope :participating, -> (user) do
    where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id))
  end

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :shop

  mount_uploader :image, PaymentUploader

end

app/models/personal_message.rb
class PersonalMessage < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates :body, presence: true

  after_create_commit do
    conversation.touch
    NotificationBroadcastJob.perform_later(self)
  end

  def receiver
    if conversation.author == conversation.receiver || conversation.receiver == user
      conversation.author
    else
      conversation.receiver
    end
  end
  
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :shop

  mount_uploader :image, ProductUploader

  validates :name, presence: true
  validates :price, presence: true

end

app/models/shop.rb
require 'elasticsearch/model'

class Shop < ApplicationRecord
  if Rails.env.production?
    Elasticsearch::Model.client = Elasticsearch::Client.new url: ENV['BONSAI_URL'], log: true
  end
  include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks
  after_commit on: [:create] do
    __elasticsearch__.index_document
  end

  after_commit on: [:update] do
    __elasticsearch__.index_document
  end

  after_commit on: [:destroy] do
    __elasticsearch__.delete_document
  end

  has_many :products, dependent: :destroy
  has_many :views, dependent: :destroy
  has_many :socials, dependent: :destroy
  has_many :payments, dependent: :destroy
  belongs_to :user
  belongs_to :category

  accepts_nested_attributes_for :products
  accepts_nested_attributes_for :socials
  accepts_nested_attributes_for :payments

  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :image, ShopUploader

  geocoded_by :location
  after_validation :geocode, if: ->(obj){ obj.location.present? and obj.location_changed? }
  reverse_geocoded_by :latitude, :longitude

  validates :title, presence: true
  validates :category_id, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  def self.search_with_elasticsearch(*args,&block)
    __elasticsearch__.search(*args, &block)
  end

end

Shop.import force: true

app/models/social.rb
class Social < ApplicationRecord
  belongs_to :shop

  mount_uploader :image, SocialUploader

  validates :link, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  has_many :shops, dependent: :destroy

  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'

  has_many :personal_messages, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorite_products, through: :favorites, source: :favorited, source_type: 'Product'
  has_many :favorite_shops, through: :favorites, source: :favorited, source_type: 'Shop'

  has_many :views, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  def name
    email.split('@')[0]
  end

  def online?
    !Redis.new.get("user_#{self.id}_online").nil?
  end

end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, except: [:index]
  before_action :check_participating!, except: [:index]

  def index
    @conversations = Conversation.participating(current_user).order('updated_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @conversations = Conversation.participating(current_user).order('updated_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
    
    @conversation = Conversation.find_by(id: params[:id])
    @personal_message = PersonalMessage.new
  end

  private

  def set_conversation
    @conversation = Conversation.find_by(id: params[:id])
  end

  def check_participating!
    redirect_to root_path unless @conversation && @conversation.participates?(current_user)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper

  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}' data-img-src='#{gravatar_image_url(user.email, size: 50)}'>#{user.email}</option>"
    end
    s.html_safe
  end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/socials_helper.rb
module SocialsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/views/conversations/_conversation.html.slim
- if controller_name == 'personal_messages'
  - @conversations.each do |conversation|
    = link_to conversation_path(conversation), class: "messages__chats__coverstaion"
      .messages__chats__coverstaion__name #{online_status conversation.with(current_user)}
      .messages__chats__coverstaion__content = conversation.personal_messages.last.body.truncate(50).html_safe

- else
  = link_to conversation_path(conversation), class: "messages__chats__coverstaion"
    .messages__chats__coverstaion__name #{online_status conversation.with(current_user)}
    .messages__chats__coverstaion__content = conversation.personal_messages.last.body.truncate(50).html_safe

app/views/conversations/_participants.html.slim
- conversation.participants.each do |participant|
  - unless participant == current_user
    = gravatar_for participant

app/views/conversations/index.html.slim
.messages
  .container
    .row.white-bg
      .col.col--auto
        .messages__wrapper
          .messages__head
            .h1-title Messages
          .row
            .messages__chats
              = render @conversations
            .messages__content
              

app/views/conversations/index.js.erb
$('#conversations').replaceWith('<%= j render @conversations %>');

app/views/conversations/show.html.slim
.messages
  .container
    .row.white-bg
      .col.col--auto
        .messages__wrapper
          .messages__head
            .h1-title Messages
          .row
            .messages__chats
              = render @conversations
            .messages__content
          
              #conversation-main
                #conversation-body data-conversation-id="#{@conversation.id}" 
                  = render @conversation.personal_messages
                
                = form_for @personal_message do |f|
                  = hidden_field_tag 'conversation_id', @conversation.id
                  = f.text_area :body
                  button type="submit" 
                    i.ico.ico-chat-btn