config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/:id/welcome', to: "users/registrations#welcome", as: :user_welcome
    get 'users/:id/myshops', to: "users/registrations#myshops", as: :my_shops
  end

  # static pages
  root to: "static#index"
  get '/about', to: "static#about"
  get '/contact', to: "static#contact"
  get '/faq', to: "static#faq"
  get '/terms', to: "static#terms"


  resources :shops
  resources :products
  resources :categories

  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  resources :favorite_products, only: [:index, :create, :destroy]
  resources :favorite_shops, only: [:index, :create, :destroy]
  resources :views, only: [:index]

  resources :socials, only: [:destroy]
  resources :payments, only: [:destroy]

  mount ActionCable.server => '/cable'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/banner.rb
class Banner < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :shops

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

  validates :author, uniqueness: {scope: :receiver}

  scope :participating, -> (user) do
    where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id))
  end

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :shop

  mount_uploader :image, PaymentUploader

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :shop

  mount_uploader :image, ProductUploader

  validates :name, presence: true
  validates :price, presence: true

end

app/models/shop.rb
require 'elasticsearch/model'

class Shop < ApplicationRecord
  if Rails.env.production?
    Elasticsearch::Model.client = Elasticsearch::Client.new url: ENV['BONSAI_URL'], log: true
  end
  include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks
  after_commit on: [:create] do
    __elasticsearch__.index_document
  end

  after_commit on: [:update] do
    __elasticsearch__.index_document
  end

  after_commit on: [:destroy] do
    __elasticsearch__.delete_document
  end

  has_many :products, dependent: :destroy
  has_many :views, dependent: :destroy
  has_many :socials, dependent: :destroy
  has_many :payments, dependent: :destroy
  belongs_to :user
  belongs_to :category

  accepts_nested_attributes_for :products
  accepts_nested_attributes_for :socials
  accepts_nested_attributes_for :payments

  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :image, ShopUploader

  geocoded_by :location
  after_validation :geocode, if: ->(obj){ obj.location.present? and obj.location_changed? }
  reverse_geocoded_by :latitude, :longitude

  validates :title, presence: true
  validates :category_id, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  def self.search_with_elasticsearch(*args,&block)
    __elasticsearch__.search(*args, &block)
  end

end

Shop.import force: true

app/models/social.rb
class Social < ApplicationRecord
  belongs_to :shop

  mount_uploader :image, SocialUploader

  validates :link, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  has_many :shops, dependent: :destroy

  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'

  has_many :personal_messages, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorite_products, through: :favorites, source: :favorited, source_type: 'Product'
  has_many :favorite_shops, through: :favorites, source: :favorited, source_type: 'Shop'

  has_many :views, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  def name
    email.split('@')[0]
  end

  def online?
    !Redis.new.get("user_#{self.id}_online").nil?
  end

end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/helpers/messages_helper.rb
module MessagesHelper

  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}' data-img-src='#{gravatar_image_url(user.email, size: 50)}'>#{user.email}</option>"
    end
    s.html_safe
  end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/socials_helper.rb
module SocialsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[charset="UTF-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"]
    - if content_for?(:head)
      = yield :head
    - else
      title
        | Winsouq
      meta[name="description" content=""]
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body

    - if content_for?(:header)
      = yield :header
    - else
      = render "shared/header"
    - if notice
      .alert.alert--notice
        .container
          .row
            .col.col--auto
              = notice
    - if alert
      .alert.alert--alert
        .container
          .row
            .col.col--auto
              = alert
            
    = yield
  - if content_for?(:footer)
    = yield :footer
  - else
    = render "shared/footer"

app/views/shared/_footer.html.slim
/! BANNER
.banner
  .container
    .row
      .col.col--auto.text-center
        .banner__text The <span>leading online platform</span> for home businesses to advertise themselves and their products.

/! FOOTER
footer.footer
  .container
    .row.row--column--tablet
      .col.col--2-6
        .footer__heading WINSHOP
        .footer__links
          = link_to "About us", about_path
          = link_to "Contact us", contact_path
          = link_to "FAQ", faq_path
          = link_to "Terms & Conditions", terms_path

      .col.col--2-6
        .footer__heading Account
        .footer__links
          - if user_signed_in?
            = link_to "Account (Dashboard)", user_welcome_path(current_user.id)
            = link_to "Edit Profile", edit_user_registration_path
            = link_to "Sign Out", destroy_user_session_path, :method => :delete
          - else
            = link_to "Sign Up", new_user_registration_path
            = link_to "Sign In", new_user_session_path
            = link_to "Restore password", new_user_password_path
          
        
      .col.col--2-6
        .footer__heading.footer__heading--centrify CONTACT US
        .footer__contacts
          .footer__contacts__phone 
            a href='tel:' 588 125 4666
          .footer__contacts__email 
            a href='mailto:' support@yourdomain.com
          .footer__contacts__adress 5 Place Road Park <br> New York 24856
        
      

app/views/shared/_header.html.slim
header.header
  - if user_signed_in?
    #current-user
  .container
    .row
      .col.col--auto
        .header__wrapper
          .header__logo
            = link_to root_path
              i.ico.ico-logo
          .header__menu
            ul
              li
                = link_to "Home", root_path
              li
                = link_to "Shop", shops_path
              li
                = link_to "Contact us", contact_path
              li
                - if user_signed_in?
                  = link_to "Account", user_welcome_path(current_user.id)
                  ul.header__menu__drop
                    li
                      = link_to "Dashboard", user_welcome_path(current_user.id)
                    li
                      = link_to "Messages", conversations_path
                    hr
                    li
                      = link_to "Sign Out", destroy_user_session_path, :method => :delete
                - else
                  = link_to "Sign up", new_user_registration_path
          
          button.hamburger.hamburger--squeeze type="button" 
            span.hamburger-box
              span.hamburger-inner
            
.mobile-nav
  .container
    .mobile-nav__list
      ul
        li
          = link_to "Home", root_path
        li
          = link_to "Shop", shops_path
        li
          = link_to "Contact us", contact_path
        - if user_signed_in?
          li
            = link_to "Account", user_welcome_path(current_user.id)
          li
            = link_to "Messages", conversations_path
          li
            = link_to "Sign Out", destroy_user_session_path, :method => :delete
        - else
          li
            = link_to "Sign up", new_user_registration_path

app/views/views/index.html.slim
- content_for :head do
  title Viewed shops
  
.shop
  .container
    .row
      .col.col--auto

      .shop__content
        .h1-title Viewed shops
        
        - @shops.each do |shop|
          .shop__listing data-link=url_for(shop)
            .shop__listing__image
              = image_tag shop.image.thumb
            .shop__listing__content
              .shop__listing__name = shop.title
              .shop__listing__location = shop.location
              .shop__listing__contacts
                span
                  = shop.email
                  |  | 
                span
                  = shop.phone
                  |  | 
                span
                  = shop.phone_2
                  |  | 
                span
                  = shop.contacts

              .shop__listing__description = sanitize(shop.description, :tags=>[]).truncate(200, :separator => " ").html_safe
              .shop__listing__actions
                - if current_user && current_user.id == shop.user.id
                  = link_to 'Edit', edit_shop_path(shop), class: 'btn btn--secondary'
                = link_to 'More details', shop, class: 'btn btn--secondary'